import { describe,expect,it } from "vitest";
import type { HarmonyEvent } from "../model";
import { stradellaColumn, stradellaMovementCost, STRADELLA_BUTTONS } from "../instrument/stradella";
import { LEGACY_ACCOMPANIMENT_TEMPLATES, LEGACY_BASS_LINE_TEMPLATES } from "../patterns/accompanimentTemplates";
import { defaultTrainingRequest } from "../training/trainingIntent";
import { generateBass } from "./generateBass";
import { generateExercise } from "./generateExercise";

const tonic=(degree:1|2|3|4|5|6|7=1):HarmonyEvent=>({id:"h",onset:0,duration:1920,rootDegree:{degree,alteration:0,octaveOffset:0},quality:"major",function:"tonic",symbol:"I"});

describe("legacy accompaniment migration",()=>{
 it("retains the old 4/4 polka attacks, buttons, and exact FR-1XB MIDI voicings",()=>{const request=defaultTrainingRequest();request.leftHand.accompanimentStyle="polka";const events=generateBass({tonic:"C",mode:"major"},{beats:4,beatUnit:4},[tonic()],request);expect(events.map(event=>[event.onset,event.duration,event.metadata.stradellaButton])).toEqual([[0,480,"C fundamental"],[480,480,"C major"],[960,480,"G fundamental"],[1440,480,"C major"]]);expect(events.map(event=>event.pitches.map(pitch=>pitch.name))).toEqual([["C3"],["C3","E3","G3"],["G3"],["C3","E3","G3"]]);expect(events.every(event=>event.metadata.accompanimentTemplateId==="legacy-polka-4")).toBe(true);});
 it("transposes the physical pattern while preserving its relationships and device voicings",()=>{const request=defaultTrainingRequest();request.leftHand.accompanimentStyle="polka";const events=generateBass({tonic:"D",mode:"major"},{beats:4,beatUnit:4},[tonic()],request);expect(events.map(event=>event.metadata.stradellaButton)).toEqual(["D fundamental","D major","A fundamental","D major"]);expect(events.map(event=>event.pitches.map(pitch=>pitch.name))).toEqual([["D3"],["D3","F#3","A3"],["A3"],["D3","F#3","A3"]]);});
 it("retains combined tango and swing bass-plus-chord attacks",()=>{const request=defaultTrainingRequest();for(const style of ["tango","swing"] as const){request.leftHand.accompanimentStyle=style;const events=generateBass({tonic:"C",mode:"major"},{beats:4,beatUnit:4},[tonic()],request);expect(events.some(event=>event.metadata.stradellaButton?.includes("bass + C chord"))).toBe(true);}});
 it("preserves every legacy chord-button quality and voicing",()=>{const request=defaultTrainingRequest();request.leftHand.accompanimentStyle="bassChord";const expected={major:["C3","E3","G3"],minor:["C3","D#3","G3"],dominant7:["C3","E3","A#3","G3"],diminished:["C3","D#3","A3","F#3"]} as const;for(const [quality,pitches] of Object.entries(expected)){const harmony={...tonic(),quality:quality as HarmonyEvent["quality"]};const chord=generateBass({tonic:"C",mode:"major"},{beats:4,beatUnit:4},[harmony],request)[1]!;expect(chord.pitches.map(pitch=>pitch.name)).toEqual(pitches);}});
 it("preserves the old two-measure 3/4 root/fifth PolkaAlt cycle",()=>{const request=defaultTrainingRequest();request.leftHand.accompanimentStyle="polka";const harmony=[{...tonic(),duration:1440},{...tonic(),id:"h2",onset:1440,duration:1440}];const events=generateBass({tonic:"C",mode:"major"},{beats:3,beatUnit:4},harmony,request);expect(events.filter((_,index)=>index%3===0).map(event=>event.metadata.stradellaButton)).toEqual(["C fundamental","G fundamental"]);});
 it("models the FR-1XB Stradella geometry independently of pitch distance",()=>{expect(stradellaColumn("C")).toBe(5);expect(stradellaColumn("G")).toBe(6);expect(stradellaMovementCost("C","G")).toBeCloseTo(1/6);expect(STRADELLA_BUTTONS).toHaveLength(72);});
 it("actively realizes the descending counterbass line",()=>{const request=defaultTrainingRequest();request.leftHand.accompanimentStyle="polka";request.leftHand.templateId="legacy-tonic-pedal-descending";const harmony=Array.from({length:4},(_,index)=>({...tonic(),id:`h${index}`,onset:index*1440,duration:1440}));const events=generateBass({tonic:"C",mode:"major"},{beats:3,beatUnit:4},harmony,request);expect(events.filter((_,index)=>index%3===0).map(event=>event.metadata.stradellaButton)).toEqual(["C fundamental","B counterbass","A counterbass","G fundamental"]);expect(events.every(event=>event.metadata.accompanimentTemplateId==="legacy-tonic-pedal-descending")).toBe(true);});
 it("actively realizes the I-to-IV counterbass transition",()=>{const request=defaultTrainingRequest();request.leftHand.templateId="legacy-transition-to-IV";const harmony=[1,1,1,4].map((degree,index)=>({...tonic(degree as 1|4),id:`h${index}`,onset:index*1440,duration:1440}));const events=generateBass({tonic:"C",mode:"major"},{beats:3,beatUnit:4},harmony,request);expect(events.filter(event=>event.pitches.length===1).map(event=>event.metadata.stradellaButton)).toEqual(["C fundamental","G fundamental","C fundamental","D counterbass","E counterbass","F fundamental"]);});
 it("actively realizes the fixed-key diminished transition with its original buttons",()=>{const request=defaultTrainingRequest();request.leftHand.templateId="legacy-bb-fdim-line";const qualities=["major","diminished","diminished","diminished","major","dominant7"] as const;const degrees=[1,5,5,5,5,3] as const;const harmony=degrees.map((degree,index):HarmonyEvent=>({...tonic(degree),id:`h${index}`,onset:index*1440,duration:1440,quality:qualities[index]!,symbol:["I","v°","v°","v°","V","III7"][index]!}));const events=generateBass({tonic:"Bb",mode:"major"},{beats:3,beatUnit:4},harmony,request);expect(events.filter((_,index)=>index%3===0).map(event=>event.metadata.stradellaButton)).toEqual(["Bb fundamental","B counterbass","G fundamental","G fundamental","C fundamental","D fundamental"]);expect(events[4]!.pitches.map(pitch=>pitch.name)).toEqual(["F2","G#3","D3","B3"]);});
 it("makes selected special lines prescribe harmony before either hand is generated",()=>{const request=defaultTrainingRequest();request.leftHand.templateId="legacy-bb-fdim-line";request.tonal.keys=["Bb major"];request.tonal.selection="fixed";request.rhythm.meters=[{beats:3,beatUnit:4}];request.measures=6;const exercise=generateExercise(request,81);expect(exercise.metadata.progressionId).toBe("legacy-bb-fdim-line");expect(exercise.harmony.map(event=>[event.rootDegree.degree,event.quality])).toEqual([[1,"major"],[5,"diminished"],[5,"diminished"],[5,"diminished"],[5,"major"],[3,"dominant7"]]);expect(new Set(exercise.leftHand.map(event=>event.metadata.accompanimentTemplateId))).toEqual(new Set(["legacy-bb-fdim-line"]));expect(exercise.rightHand.every(event=>exercise.harmony.some(harmony=>harmony.id===event.metadata.harmonyId))).toBe(true);});
 it("normalizes incompatible settings when an explicit curated line is selected",()=>{const request=defaultTrainingRequest();request.leftHand.templateId="legacy-bb-fdim-line";request.leftHand.enabled=false;request.tonal.keys=["C major","G major"];request.rhythm.meters=[{beats:4,beatUnit:4}];request.measures=2;const exercise=generateExercise(request,91);expect(exercise.tonalContext).toEqual({tonic:"Bb",mode:"major"});expect(exercise.meter).toEqual({beats:3,beatUnit:4});expect(exercise.phrase).toHaveLength(6);expect(exercise.leftHand.length).toBeGreaterThan(0);});
 it("preserves provenance for ordinary and multi-measure curated patterns",()=>{expect(LEGACY_ACCOMPANIMENT_TEMPLATES.every(template=>template.legacySource.length>0)).toBe(true);expect(LEGACY_BASS_LINE_TEMPLATES.find(template=>template.id==="legacy-tonic-pedal-descending")?.legacySource).toBe("C/C C/B C/A C/G");expect(LEGACY_BASS_LINE_TEMPLATES.find(template=>template.id==="legacy-bb-fdim-line")?.fixedKey).toBe("Bb major");});
});
