import { describe,expect,it } from "vitest";
import { accordionProfile } from "../instrument/accordionProfile";
import { chordPitches } from "../music/harmony";
import { createExpectedTimeline } from "../performance/timeline";
import { exerciseToAbc } from "../../adapters/abc/exerciseToAbc";
import type { AccompanimentStyle } from "../model";
import { defaultTrainingRequest } from "../training/trainingIntent";
import { generateBass } from "./generateBass";
import { generateExercise } from "./generateExercise";
import { validateExercise } from "./validateExercise";

describe("musical structure",()=>{
 it("uses a major dominant and truthful symbols in minor",()=>{const request=defaultTrainingRequest();request.tonal.keys=["A minor"];request.harmony.progressionVocabulary=["I-IV-V-I"];const exercise=generateExercise(request,12);expect(exercise.harmony.map(x=>[x.symbol,x.quality])).toEqual([["i","minor"],["iv","minor"],["V","major"],["i","minor"]]);});
 it("articulates harmony on beats and resolves the cadence to tonic",()=>{const exercise=generateExercise(defaultTrainingRequest(),42);for(const event of exercise.rightHand.filter(e=>e.pitches.length&&e.metadata.metricStrength!=="weak"&&!e.metadata.chromatic)){const harmony=exercise.harmony.find(h=>h.id===event.metadata.harmonyId)!;const chordPitchClasses=chordPitches(exercise.tonalContext,harmony).map(p=>p.midi%12);expect(chordPitchClasses).toContain(event.pitches[0]!.midi%12);}const last=exercise.rightHand.filter(e=>e.pitches.length).at(-1)!;expect(last.metadata.scaleDegree?.degree).toBe(1);expect(last.metadata.chromatic).toBe(false);});
 it("raises the leading tone when melody articulates V in minor",()=>{const request=defaultTrainingRequest();request.tonal.keys=["A minor"];request.harmony.progressionVocabulary=["I-IV-V-I"];request.tonal.chromaticism=0;request.challenge.density=0;const exercise=generateExercise(request,73);const dominant=exercise.harmony.find(h=>h.rootDegree.degree===5)!;for(const event of exercise.rightHand.filter(e=>e.metadata.harmonyId===dominant.id&&e.pitches.length&&e.metadata.metricStrength!=="weak")){expect(chordPitches(exercise.tonalContext,dominant).map(p=>p.midi%12)).toContain(event.pitches[0]!.midi%12);if(event.metadata.scaleDegree?.degree===7)expect(event.metadata.scaleDegree.alteration).toBe(1);}});
 it("carries the A motif into A-prime as a real relation",()=>{const exercise=generateExercise(defaultTrainingRequest(),99);const first=new Set(exercise.rightHand.filter(e=>e.onset<exercise.harmony[0]!.duration).map(e=>e.metadata.motifId));const second=new Set(exercise.rightHand.filter(e=>e.onset>=exercise.harmony[0]!.duration&&e.onset<exercise.harmony[0]!.duration*2).map(e=>e.metadata.motifId));expect(first).toEqual(new Set(["motif-0"]));expect(second).toEqual(new Set(["motif-A"]));expect(new Set(exercise.rightHand.slice(0,4).map(e=>e.metadata.patternId))).toEqual(new Set(exercise.rightHand.filter(e=>e.onset>=exercise.harmony[0]!.duration&&e.onset<exercise.harmony[0]!.duration*2).map(e=>e.metadata.patternId)));});
 it("realizes accompaniment styles with distinct event grids",()=>{const request=defaultTrainingRequest();const harmony=generateExercise(request,7).harmony.slice(0,1);const styles:AccompanimentStyle[]=["bassChord","alternatingBass","waltz","tango","swing"];const signatures=styles.map(style=>{request.leftHand.accompanimentStyle=style;return generateBass({tonic:"C",mode:"major"},{beats:4,beatUnit:4},harmony,request).map(e=>`${e.onset}:${e.duration}:${e.metadata.rhythmCellId}`).join("|");});expect(new Set(signatures).size).toBe(styles.length);});
 it("rejects gaps in hand timelines",()=>{const exercise=generateExercise(defaultTrainingRequest(),4);exercise.rightHand[1]!.onset+=1;expect(validateExercise(exercise,accordionProfile).valid).toBe(false);});
 it("realizes configured ties without requiring a second MIDI attack",()=>{const request=defaultTrainingRequest();request.rhythm.smallestSubdivision="quarter";request.rhythm.tieDensity=1;request.rhythm.restDensity=0;request.rhythm.syncopation=0;const exercise=generateExercise(request,123);const continuations=exercise.rightHand.filter(e=>e.metadata.tieFromPrevious);expect(continuations.length).toBeGreaterThan(0);for(const continuation of continuations){const previous=exercise.rightHand[exercise.rightHand.indexOf(continuation)-1]!;expect(previous.metadata.tieToNext).toBe(true);expect(continuation.pitches).toEqual(previous.pitches);}expect(exerciseToAbc(exercise)).toMatch(/[A-Ga-g][,']*\d*- /);expect(createExpectedTimeline(exercise).filter(e=>e.hand==="right")).toHaveLength(exercise.rightHand.filter(e=>e.pitches.length&&!e.metadata.tieFromPrevious).length);});
});
